---
- hosts: 192.168.10.5
         192.168.10.4
  become: true
  tasks:

  - name: install httpd package
    dnf:
      name: httpd
      state: latest
  - name: enable service
    service:
      name: httpd
      state: started
  handlers:
  - name: restart httpd service
    service:
      name: httpd
      state: restarted
