---
- hosts: 192.168.10.5
  become: true
  tasks:

  - name: install apache and php packages for RedHat
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes

